# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InterfaceConnectionSerializer(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, interface_a=None, interface_b=None, connection_status=None):
        """
        InterfaceConnectionSerializer - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'interface_a': 'str',
            'interface_b': 'str',
            'connection_status': 'bool'
        }

        self.attribute_map = {
            'id': 'id',
            'interface_a': 'interface_a',
            'interface_b': 'interface_b',
            'connection_status': 'connection_status'
        }

        self._id = id
        self._interface_a = interface_a
        self._interface_b = interface_b
        self._connection_status = connection_status


    @property
    def id(self):
        """
        Gets the id of this InterfaceConnectionSerializer.


        :return: The id of this InterfaceConnectionSerializer.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this InterfaceConnectionSerializer.


        :param id: The id of this InterfaceConnectionSerializer.
        :type: int
        """

        self._id = id

    @property
    def interface_a(self):
        """
        Gets the interface_a of this InterfaceConnectionSerializer.


        :return: The interface_a of this InterfaceConnectionSerializer.
        :rtype: str
        """
        return self._interface_a

    @interface_a.setter
    def interface_a(self, interface_a):
        """
        Sets the interface_a of this InterfaceConnectionSerializer.


        :param interface_a: The interface_a of this InterfaceConnectionSerializer.
        :type: str
        """

        self._interface_a = interface_a

    @property
    def interface_b(self):
        """
        Gets the interface_b of this InterfaceConnectionSerializer.


        :return: The interface_b of this InterfaceConnectionSerializer.
        :rtype: str
        """
        return self._interface_b

    @interface_b.setter
    def interface_b(self, interface_b):
        """
        Sets the interface_b of this InterfaceConnectionSerializer.


        :param interface_b: The interface_b of this InterfaceConnectionSerializer.
        :type: str
        """

        self._interface_b = interface_b

    @property
    def connection_status(self):
        """
        Gets the connection_status of this InterfaceConnectionSerializer.


        :return: The connection_status of this InterfaceConnectionSerializer.
        :rtype: bool
        """
        return self._connection_status

    @connection_status.setter
    def connection_status(self, connection_status):
        """
        Sets the connection_status of this InterfaceConnectionSerializer.


        :param connection_status: The connection_status of this InterfaceConnectionSerializer.
        :type: bool
        """

        self._connection_status = connection_status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
