# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class RackNestedSerializer(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, facility_id=None, display_name=None):
        """
        RackNestedSerializer - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'name': 'str',
            'facility_id': 'str',
            'display_name': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'facility_id': 'facility_id',
            'display_name': 'display_name'
        }

        self._id = id
        self._name = name
        self._facility_id = facility_id
        self._display_name = display_name


    @property
    def id(self):
        """
        Gets the id of this RackNestedSerializer.


        :return: The id of this RackNestedSerializer.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this RackNestedSerializer.


        :param id: The id of this RackNestedSerializer.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this RackNestedSerializer.


        :return: The name of this RackNestedSerializer.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this RackNestedSerializer.


        :param name: The name of this RackNestedSerializer.
        :type: str
        """

        self._name = name

    @property
    def facility_id(self):
        """
        Gets the facility_id of this RackNestedSerializer.


        :return: The facility_id of this RackNestedSerializer.
        :rtype: str
        """
        return self._facility_id

    @facility_id.setter
    def facility_id(self, facility_id):
        """
        Sets the facility_id of this RackNestedSerializer.


        :param facility_id: The facility_id of this RackNestedSerializer.
        :type: str
        """

        self._facility_id = facility_id

    @property
    def display_name(self):
        """
        Gets the display_name of this RackNestedSerializer.


        :return: The display_name of this RackNestedSerializer.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """
        Sets the display_name of this RackNestedSerializer.


        :param display_name: The display_name of this RackNestedSerializer.
        :type: str
        """

        self._display_name = display_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
