# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class WriteRoleSerializer(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, slug=None, weight=None):
        """
        WriteRoleSerializer - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'slug': 'str',
            'weight': 'int'
        }

        self.attribute_map = {
            'name': 'name',
            'slug': 'slug',
            'weight': 'weight'
        }

        self._name = name
        self._slug = slug
        self._weight = weight


    @property
    def name(self):
        """
        Gets the name of this WriteRoleSerializer.


        :return: The name of this WriteRoleSerializer.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this WriteRoleSerializer.


        :param name: The name of this WriteRoleSerializer.
        :type: str
        """

        self._name = name

    @property
    def slug(self):
        """
        Gets the slug of this WriteRoleSerializer.


        :return: The slug of this WriteRoleSerializer.
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """
        Sets the slug of this WriteRoleSerializer.


        :param slug: The slug of this WriteRoleSerializer.
        :type: str
        """

        self._slug = slug

    @property
    def weight(self):
        """
        Gets the weight of this WriteRoleSerializer.


        :return: The weight of this WriteRoleSerializer.
        :rtype: int
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """
        Sets the weight of this WriteRoleSerializer.


        :param weight: The weight of this WriteRoleSerializer.
        :type: int
        """

        if not weight:
            raise ValueError("Invalid value for `weight`, must not be `None`")
        if weight > 32767.0:
            raise ValueError("Invalid value for `weight`, must be a value less than or equal to `32767.0`")
        if weight < 0.0:
            raise ValueError("Invalid value for `weight`, must be a value greater than or equal to `0.0`")

        self._weight = weight

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
